# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup the docs
    - name: Setup
      run: |
        sudo ./docs setup
        sudo ./docs generate
        

    # This is the post commit script
    - name: Deploy
      run: |
        current_branch="$(git rev-parse --abbrev-ref HEAD)"
        branch_to_deploy="master"
        if [ "$current_branch" = "$branch_to_deploy" ]; then
          echo "Updating date in index.adoc"
          ./docs update-date
          echo "removing output directory ('out')"
          sudo rm -rf ./out
          echo "getting gh-pages repository..."
          old_git_dir="$GIT_DIR"
          unset GIT_DIR
          old_git_working_dir="$GIT_WORK_TREE"
          unset GIT_WORK_TREE
          git clone https://github.com/CAU-Kiel-Tech-Inf/socha-enduser-docs --branch gh-pages --single-bran ch out
          echo "generating static pages..."
          ./docs generate pdf
          echo "putting new version in gh-pages branch"
          cd out
          touch .nojekyll
          git add -A
          git commit -a -u -m "automatically updated generated files on commit to master"
          echo "deploying to github"
          git push origin
          cd ..
          rm -rf ./out
          GIT_DIR="$old_git_dir"
          GIT_WORK_TREE="$old_git_working_dir"
        fi
