name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build documentation
      id: build
      run: |
        cd hyperbook
        npx hyperbook build
        echo "::set-output name=message::$(git log --format='Deploy %h %<|(50,trunc)%f' -1)"

    - name: Push generated documentation to live branch
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: live
        publish_dir: hyperbook/.hyperbook/out
        user_name: "GitHub Publish Workflow"
        user_email: info@software-challenge.de
        full_commit_message: ${{steps.build.outputs.message}}
