name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Hyperbook
      run: |
        cd hyperbook
        npx hyperbook setup

    - name: Checkout live branch
      uses: actions/checkout@v3
      with:
        ref: live
        path: hyperbook/live

    - name: Build documentation
      run: |
        cd hyperbook/
        npx hyperbook build
        rm -rf live/* .hyperbook/out/_next
        cp -r .hyperbook/out/* live/

    - name: Commit changes
      run: |
        cd hyperbook/
        message="$(git log --format='Deploy %h %<|(50,trunc)%f' -1)"
        cd live/
        git config user.email "info@software-challenge.de"
        git config user.name "GitHub Publish Action"
        git add --all
        git commit -m "$message"

    - name: Push generated documentation to live branch
      run: |
        cd hyperbook/live/
        git push https://socha-bot:${{ secrets.ACCESS_TOKEN }}@github.com/software-challenge/docs
