name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup the docs
    - name: Setup
      run: |
        sudo ./docs setup
        sudo ./docs generate
      
    # Deploy the docs to the gh-pages website
    - name: Deploy
      run: |
        echo "Updating date in index.adoc"
          ./docs update-date
          echo "removing output directory ('out')"
          sudo rm -rf ./out
          echo "getting gh-pages repository..."
          old_git_dir="$GIT_DIR"
          unset GIT_DIR
          old_git_working_dir="$GIT_WORK_TREE"
          unset GIT_WORK_TREE
          git clone https://github.com/CAU-Kiel-Tech-Inf/socha-enduser-docs --branch gh-pages --single-branch out
          echo "generating static pages..."
          ./docs generate pdf
          echo "putting new version in gh-pages branch"
          cd out
          touch .nojekyll
          git config user.email "creeper99.mc@gmail.com"
          git config user.name "niklasCarstensen"
          git add -A
          git commit -a -u -m "Deploy"
          echo "deploying to github"
          git push https://niklasCarstensen:${{ secrets.GITHUB_TOKEN }}@github.com/CAU-Kiel-Tech-Inf/socha-enduser-docs
          cd ..
          rm -rf ./out
          GIT_DIR="$old_git_dir"
          GIT_WORK_TREE="$old_git_working_dir"
