name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup the docs
    - name: Generate
      run: |
        cd hyperbook
        npx hyperbook setup

        message="$(git log --format='Deploy %h %<|(50,trunc)%f' -1)"

        echo "== getting live branch..."
        git clone https://github.com/software-challenge/docs --branch live --single-branch .hyperbook/out
        npx hyperbook build

        echo "== creating commit..."
        cd .hyperbook/out
        git config user.email "info@software-challenge.de"
        git config user.name "GitHub Publish Action"
        git add --all
        git commit -m "$message"

    # Push the generated docs to the live branch
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        cd hyperbook/.hyperbook/out
        git push https://socha-bot:${{ secrets.ACCESS_TOKEN }}@github.com/software-challenge/docs

    - name: Cleanup
      run: |
        echo "== cleaning up"
        rm -rf ./.hyperbook
