name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup
      run: |
        cd hyperbook
        npx hyperbook setup

    - name: Checkout live branch
      uses: actions/checkout@v3
      with:
        ref: live
        path: hyperbook/live

    # Setup the doc
    - name: Generate
      run: |
        message="$(git log --format='Deploy %h %<|(50,trunc)%f' -1)"
        cd hyperbook

        echo "== updating live branch..."
        npx hyperbook build
        cp -r .hyperbook/out/* live/
        cd live/

        echo "== creating commit..."
        git config user.email "info@software-challenge.de"
        git config user.name "GitHub Publish Action"
        git add --all
        git commit -m "$message"

    # Push the generated docs to the live branch
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        pwd
        cd hyperbook/.hyperbook/out
        git push https://socha-bot:${{ secrets.ACCESS_TOKEN }}@github.com/software-challenge/docs
